global:
  resolve_timeout: 5m

route:
  receiver: 'webhook'
  routes:
    - match:
        severity: 'critical'
      receiver: 'team-notifications'

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://webhook-service:5000/alert'
  - name: 'team-notifications'
    email_configs:
      - to: 'team@example.com'

