version: '3'

services:
  prometheus:
    image: prom/prometheus
    user: 1000:1000
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/root/montoring-cronjob-docker-grafana-promethos/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

networks:
  default:
    external:
      name: monitoring

